// SGK KNTT & Global Success (Tiếng Anh) – Danh sách bài học (hardcoded)
const LESSONS_DB = {
'1':{
'Toán':['Bài 1: Các số 1, 2, 3','Bài 2: Các số 4, 5','Bài 3: Các số 6, 7, 8, 9','Bài 4: Số 0','Bài 5: Số 10','Bài 6: Phép cộng trong phạm vi 10','Bài 7: Phép trừ trong phạm vi 10','Bài 8: Các số từ 11 đến 20','Bài 9: Các số từ 21 đến 99','Bài 10: Số 100','Bài 11: Phép cộng và phép trừ trong phạm vi 20','Bài 12: Phép cộng và phép trừ trong phạm vi 100','Bài 13: Các hình phẳng – Điểm. Đoạn thẳng','Bài 14: Hình vuông. Hình tròn. Hình tam giác','Bài 15: Đo độ dài','Bài 16: Thời gian – Ngày, giờ','Bài 17: Nhiều hơn. Ít hơn. Bằng nhau','Bài 18: Ôn tập cuối năm'],
'Tiếng Việt':['Bài 1: Làm quen với âm và chữ (a, b, c)','Bài 2: Các âm và chữ d, đ, e, ê','Bài 3: Các âm và chữ g, h, i, k','Bài 4: Các âm và chữ l, m, n, o, ô','Bài 5: Các âm và chữ ơ, p, q, r','Bài 6: Các âm và chữ s, t, u, ư','Bài 7: Các âm và chữ v, x, y','Bài 8: Vần an, ăn, ân','Bài 9: Vần en, ên, in, un','Bài 10: Vần ong, ông, ung','Bài 11: Vần ang, ăng, âng','Bài 12: Vần inh, ênh, anh','Bài 13: Vần ach, êch, ich','Bài 14: Đọc – Mái trường mến yêu','Bài 15: Đọc – Gia đình em','Bài 16: Đọc – Thiên nhiên kì diệu','Bài 17: Đọc – Con vật quanh em','Bài 18: Đọc – Em lớn lên mỗi ngày'],
'Đạo đức':['Bài 1: Em là học sinh lớp 1','Bài 2: Gọn gàng sạch sẽ','Bài 3: Gia đình em','Bài 4: Yêu quý ông bà, cha mẹ','Bài 5: Quan tâm chăm sóc ông bà','Bài 6: Lễ phép với người lớn tuổi','Bài 7: Giữ trật tự vệ sinh nơi công cộng','Bài 8: Em yêu thiên nhiên','Bài 9: Chăm chỉ học tập','Bài 10: Thật thà, ngay thẳng'],
'Tự nhiên và Xã hội':['Bài 1: Cơ thể em','Bài 2: Giữ gìn cơ thể sạch sẽ','Bài 3: Bảo vệ mắt và tai','Bài 4: Ăn uống điều độ','Bài 5: Gia đình em','Bài 6: Các thành viên trong gia đình','Bài 7: Ngôi nhà của em','Bài 8: Đồ dùng trong nhà','Bài 9: An toàn trong nhà','Bài 10: Trường học của em','Bài 11: Các thành viên trong trường','Bài 12: Hoạt động ở trường','Bài 13: Cây xung quanh em','Bài 14: Con vật quanh em','Bài 15: Bầu trời và mặt đất','Bài 16: Thời tiết'],
'Hoạt động trải nghiệm':['Bài 1: Em vào lớp 1','Bài 2: Tự phục vụ bản thân','Bài 3: Gia đình thân yêu','Bài 4: Trường học thân thiện','Bài 5: Em với thiên nhiên','Bài 6: Lễ hội và truyền thống'],
'Tiếng Anh':['Unit 1: In the school playground','Unit 2: In the dining room','Unit 3: At the street market','Unit 4: In the bedroom','Unit 5: At the classroom','Unit 6: Around the school','Unit 7: In the garden','Unit 8: At the park','Unit 9: In the shop','Unit 10: At the zoo','Unit 11: At the bus stop','Unit 12: By the lake','Unit 13: In the toy shop','Unit 14: In the hospital','Unit 15: At the football match','Unit 16: At the campsite']
},
'2':{
'Toán':['Bài 1: Ôn tập các số đến 100','Bài 2: Các số đến 1000','Bài 3: Phép cộng có nhớ trong phạm vi 100','Bài 4: Phép trừ có nhớ trong phạm vi 100','Bài 5: Phép nhân','Bài 6: Bảng nhân 2, 3, 4, 5','Bài 7: Bảng nhân 6, 7, 8, 9','Bài 8: Phép chia','Bài 9: Bảng chia 2, 3, 4, 5','Bài 10: Bảng chia 6, 7, 8, 9','Bài 11: Đường thẳng. Đoạn thẳng. Tia số','Bài 12: Hình chữ nhật. Hình tứ giác','Bài 13: Chu vi hình tam giác, hình tứ giác','Bài 14: Đơn vị đo độ dài','Bài 15: Đơn vị đo khối lượng','Bài 16: Lít – Đo dung tích','Bài 17: Thời gian – Tháng, năm','Bài 18: Tiền Việt Nam'],
'Tiếng Việt':['Bài 1: Em là học sinh lớp 2','Bài 2: Gia đình','Bài 3: Trường học','Bài 4: Bạn bè','Bài 5: Thiên nhiên kì diệu','Bài 6: Bốn mùa','Bài 7: Yêu thương','Bài 8: Nội quy – Quy tắc','Bài 9: Sách và tri thức','Bài 10: Quê hương'],
'Đạo đức':['Bài 1: Yêu thương gia đình','Bài 2: Chăm sóc cha mẹ khi ốm','Bài 3: Kính trọng thầy cô','Bài 4: Hợp tác với bạn bè','Bài 5: Giúp đỡ người khó khăn','Bài 6: Bảo vệ môi trường','Bài 7: Tiết kiệm điện nước','Bài 8: Trung thực trong học tập'],
'Tự nhiên và Xã hội':['Bài 1: Cơ quan vận động','Bài 2: Cơ quan tiêu hóa','Bài 3: Ăn uống sạch sẽ','Bài 4: Phòng bệnh đường tiêu hóa','Bài 5: Gia đình em','Bài 6: Họ hàng nội ngoại','Bài 7: An toàn khi ở nhà','Bài 8: Trường em','Bài 9: Giữ vệ sinh trường học','Bài 10: Cuộc sống xung quanh','Bài 11: Thực vật','Bài 12: Động vật','Bài 13: Bầu trời ban ngày và ban đêm','Bài 14: Thời tiết và khí hậu','Bài 15: Ôn tập'],
'Hoạt động trải nghiệm':['Bài 1: Hình ảnh của em','Bài 2: Chăm sóc bản thân','Bài 3: Môi trường quanh em','Bài 4: Làm việc nhà','Bài 5: Bạn bè quanh em','Bài 6: Lễ hội quê em'],
'Tiếng Anh':['Unit 1: At my birthday party','Unit 2: In the backyard','Unit 3: At the seaside','Unit 4: In the countryside','Unit 5: In the classroom','Unit 6: On the farm','Unit 7: In the kitchen','Unit 8: In the village','Unit 9: In the grocery store','Unit 10: At the zoo','Unit 11: In the playground','Unit 12: At the cafe','Unit 13: In the maths class','Unit 14: At home','Unit 15: In the clothes shop','Unit 16: At the campsite']
},
'3':{
'Toán':['Bài 1: Ôn tập các số đến 1000','Bài 2: Các số đến 10000','Bài 3: Phép cộng các số trong phạm vi 10000','Bài 4: Phép trừ các số trong phạm vi 10000','Bài 5: Nhân số có hai chữ số với số có một chữ số','Bài 6: Chia số có hai chữ số cho số có một chữ số','Bài 7: Bảng nhân, bảng chia đã học','Bài 8: Hình học – Góc vuông, góc không vuông','Bài 9: Hình chữ nhật – Hình vuông','Bài 10: Chu vi và diện tích hình chữ nhật, hình vuông','Bài 11: Đơn vị đo độ dài – km, m, dm, cm, mm','Bài 12: Đơn vị đo khối lượng – kg, g','Bài 13: Đơn vị đo thời gian – giờ, phút, giây','Bài 14: Phân số đơn giản','Bài 15: Xem đồng hồ','Bài 16: Làm quen với thống kê số liệu'],
'Tiếng Việt':['Bài 1: Mái ấm gia đình','Bài 2: Tới trường','Bài 3: Bạn bè','Bài 4: Cộng đồng','Bài 5: Ngôi nhà chung','Bài 6: Thiên nhiên','Bài 7: Việt Nam đất nước em','Bài 8: Những người dũng cảm','Bài 9: Khoa học và đời sống','Bài 10: Em lớn lên mỗi ngày'],
'Đạo đức':['Bài 1: Kính yêu Bác Hồ','Bài 2: Yêu thương và quan tâm người thân','Bài 3: Tôn trọng phụ nữ','Bài 4: Quan tâm giúp đỡ hàng xóm','Bài 5: Tiết kiệm và bảo vệ tài nguyên','Bài 6: Bảo vệ công trình công cộng','Bài 7: Tích cực tham gia việc lớp việc trường','Bài 8: Trách nhiệm với việc làm của mình'],
'Tự nhiên và Xã hội':['Bài 1: Cơ quan hô hấp','Bài 2: Vệ sinh cơ quan hô hấp','Bài 3: Cơ quan tuần hoàn','Bài 4: Vệ sinh cơ quan tuần hoàn','Bài 5: Hoạt động thần kinh','Bài 6: Vệ sinh thần kinh','Bài 7: Các thế hệ trong gia đình','Bài 8: Họ hàng nội ngoại','Bài 9: Trường học','Bài 10: Các nghề trong xã hội','Bài 11: Làng quê và đô thị','Bài 12: An toàn khi đi xe đạp','Bài 13: Cây sống ở đâu','Bài 14: Cuộc sống hoang dã','Bài 15: Mặt trời – Ngày đêm, mùa'],
'Tin học':['Bài 1: Làm quen với máy tính','Bài 2: Bàn phím và chuột máy tính','Bài 3: Tập gõ bàn phím','Bài 4: Phần mềm học tập','Bài 5: Em vẽ trên máy tính','Bài 6: Soạn thảo văn bản đơn giản','Bài 7: Internet và tìm kiếm thông tin','Bài 8: An toàn khi dùng internet'],
'Công nghệ':['Bài 1: Nhà ở','Bài 2: Đồ dùng trong gia đình','Bài 3: Thực phẩm','Bài 4: Nấu ăn đơn giản','Bài 5: Trồng cây','Bài 6: Thủ công – Gấp, cắt, dán','Bài 7: Chăn nuôi gia đình'],
'Hoạt động trải nghiệm':['Bài 1: Trường học thân thiện','Bài 2: Em lớn lên từng ngày','Bài 3: Gia đình yêu thương','Bài 4: Quê hương tươi đẹp','Bài 5: Nghề nghiệp quanh em','Bài 6: An toàn giao thông'],
'Tiếng Anh':['Unit 1: Hello','Unit 2: Our names','Unit 3: Our friends','Unit 4: Our bodies','Unit 5: My hobbies','Unit 6: Our school','Unit 7: Classroom instructions','Unit 8: My school things','Unit 9: Colours','Unit 10: Break time activities','Unit 11: My family','Unit 12: Jobs','Unit 13: My house','Unit 14: My bedroom','Unit 15: At the dining table','Unit 16: My pets','Unit 17: Our toys','Unit 18: Playing and doing','Unit 19: Outdoor activities','Unit 20: At the summer camp']
},
'4':{
'Toán':['Bài 1: Ôn tập các số đến 100000','Bài 2: Các số đến 1000000 và lớn hơn','Bài 3: Phép cộng và phép trừ các số có nhiều chữ số','Bài 4: Phép nhân số có nhiều chữ số','Bài 5: Phép chia số có nhiều chữ số','Bài 6: Tìm số trung bình cộng','Bài 7: Biểu đồ','Bài 8: Phân số','Bài 9: Phép cộng và phép trừ phân số','Bài 10: Phép nhân và phép chia phân số','Bài 11: Góc – Đo góc','Bài 12: Hình bình hành','Bài 13: Diện tích hình bình hành','Bài 14: Hình thoi – Diện tích hình thoi','Bài 15: Đơn vị đo diện tích','Bài 16: Đơn vị đo thể tích','Bài 17: Hình hộp chữ nhật – Hình lập phương'],
'Tiếng Việt':['Bài 1: Thương người như thể thương thân','Bài 2: Măng mọc thẳng','Bài 3: Trên đôi cánh ước mơ','Bài 4: Có chí thì nên','Bài 5: Tiếng sáo diều','Bài 6: Người ta là hoa đất','Bài 7: Vẻ đẹp muôn màu','Bài 8: Những người quả cảm','Bài 9: Khám phá thế giới','Bài 10: Lý tưởng sống'],
'Đạo đức':['Bài 1: Tự trọng','Bài 2: Trung thực trong học tập và cuộc sống','Bài 3: Vượt khó trong học tập','Bài 4: Biết ơn thầy cô giáo','Bài 5: Yêu lao động','Bài 6: Kính già yêu trẻ','Bài 7: Tích cực tham gia các hoạt động nhân đạo','Bài 8: Bảo vệ môi trường'],
'Khoa học':['Bài 1: Vật và chất','Bài 2: Nước','Bài 3: Không khí','Bài 4: Ánh sáng','Bài 5: Âm thanh','Bài 6: Nhiệt','Bài 7: Trao đổi chất ở người','Bài 8: Tiêu hóa và hấp thụ','Bài 9: Tuần hoàn máu','Bài 10: Thần kinh và giác quan','Bài 11: Sinh sản ở người','Bài 12: Thực vật và động vật','Bài 13: Môi trường và tài nguyên thiên nhiên','Bài 14: Bảo vệ môi trường'],
'Lịch sử và Địa lí':['Bài 1: Làm quen với lịch sử và địa lí','Bài 2: Buổi đầu lịch sử dân tộc','Bài 3: Thời Hùng Vương','Bài 4: Đất nước thời Âu Lạc','Bài 5: Ngàn năm Bắc thuộc','Bài 6: Buổi đầu độc lập','Bài 7: Nước Đại Việt thời Lý','Bài 8: Đất nước ta','Bài 9: Thiên nhiên Việt Nam','Bài 10: Dân cư và dân tộc Việt Nam','Bài 11: Các vùng kinh tế','Bài 12: Biển đảo Việt Nam'],
'Tin học':['Bài 1: Máy tính và cuộc sống','Bài 2: Phần mềm trình chiếu','Bài 3: Tạo bài trình chiếu','Bài 4: Chèn hình ảnh và âm thanh','Bài 5: Bảng tính đơn giản','Bài 6: Lập trình kéo thả','Bài 7: Tạo hoạt hình đơn giản','Bài 8: An toàn thông tin'],
'Công nghệ':['Bài 1: Kĩ thuật trồng hoa','Bài 2: Lắp ráp mô hình kĩ thuật','Bài 3: Cắt khâu thêu','Bài 4: Chăm sóc hoa, cây cảnh','Bài 5: Lắp ghép mô hình xe','Bài 6: Thiết kế đồ chơi'],
'Hoạt động trải nghiệm':['Bài 1: Em yêu mái trường','Bài 2: Sống tự lập','Bài 3: Mái ấm gia đình','Bài 4: Yêu thương chia sẻ','Bài 5: Yêu thiên nhiên','Bài 6: Khám phá nghề nghiệp'],
'Tiếng Anh':['Unit 1: My friends','Unit 2: Time and daily routines','Unit 3: My week','Unit 4: My birthday party','Unit 5: Things we can do','Unit 6: Our school facilities','Unit 7: Our timetables','Unit 8: My favourite subjects','Unit 9: Our sports day','Unit 10: Our summer holidays','Unit 11: My home','Unit 12: Jobs','Unit 13: Appearance','Unit 14: Daily activities','Unit 15: My family\'s weekends','Unit 16: Weather','Unit 17: In the city','Unit 18: At the shopping centre','Unit 19: The animal world','Unit 20: Summer camp']
},
'5':{
'Toán':['Bài 1: Ôn tập về số tự nhiên và phân số','Bài 2: Số thập phân','Bài 3: Phép cộng và phép trừ số thập phân','Bài 4: Phép nhân số thập phân','Bài 5: Phép chia số thập phân','Bài 6: Tỉ số và tỉ số phần trăm','Bài 7: Giải toán về tỉ số phần trăm','Bài 8: Hình tam giác','Bài 9: Diện tích hình tam giác','Bài 10: Hình thang – Diện tích hình thang','Bài 11: Hình tròn – Chu vi hình tròn','Bài 12: Diện tích hình tròn','Bài 13: Hình hộp chữ nhật và hình lập phương','Bài 14: Thể tích hình hộp chữ nhật','Bài 15: Số liệu thống kê','Bài 16: Ôn tập cuối năm'],
'Tiếng Việt':['Bài 1: Việt Nam – Tổ quốc em','Bài 2: Cánh chim hòa bình','Bài 3: Con người với thiên nhiên','Bài 4: Giữ lấy màu xanh','Bài 5: Những chủ nhân tương lai','Bài 6: Vì hạnh phúc con người','Bài 7: Người ta là hoa đất','Bài 8: Những tấm gương','Bài 9: Vì cuộc sống thanh bình','Bài 10: Ôn tập và đánh giá'],
'Đạo đức':['Bài 1: Em là học sinh lớp 5','Bài 2: Có trách nhiệm về việc làm của mình','Bài 3: Có chí thì nên','Bài 4: Nhớ ơn tổ tiên','Bài 5: Tình bạn','Bài 6: Kính già yêu trẻ','Bài 7: Tôn trọng phụ nữ','Bài 8: Hợp tác với người xung quanh','Bài 9: Em yêu hòa bình','Bài 10: Em yêu Tổ quốc Việt Nam'],
'Khoa học':['Bài 1: Sự sinh sản ở thực vật','Bài 2: Sự sinh sản ở động vật','Bài 3: Năng lượng mặt trời','Bài 4: Năng lượng gió và nước chảy','Bài 5: Sử dụng năng lượng điện','Bài 6: Vật dẫn điện và vật cách điện','Bài 7: An toàn khi sử dụng điện','Bài 8: Sự sinh sản của người','Bài 9: Từ tuổi ấu thơ đến tuổi trưởng thành','Bài 10: Hệ sinh thái','Bài 11: Chuỗi thức ăn','Bài 12: Môi trường và tài nguyên','Bài 13: Bảo vệ môi trường'],
'Lịch sử và Địa lí':['Bài 1: Lịch sử và địa lí nước ta','Bài 2: Nhà nước Văn Lang – Âu Lạc','Bài 3: Thời kì Bắc thuộc','Bài 4: Đinh – Lê – Lý – Trần','Bài 5: Thời Lê sơ','Bài 6: Trịnh – Nguyễn phân tranh','Bài 7: Nhà Nguyễn','Bài 8: Việt Nam đầu thế kỉ XX','Bài 9: Cách mạng tháng Tám 1945','Bài 10: Kháng chiến chống Pháp','Bài 11: Kháng chiến chống Mỹ','Bài 12: Việt Nam sau 1975','Bài 13: Vị trí địa lí Việt Nam','Bài 14: Địa hình Việt Nam','Bài 15: Khí hậu Việt Nam','Bài 16: Sông ngòi và biển Việt Nam','Bài 17: Dân số và dân tộc','Bài 18: Các vùng kinh tế','Bài 19: Hà Nội – Thủ đô','Bài 20: Thành phố Hồ Chí Minh'],
'Tin học':['Bài 1: Thế giới số và cuộc sống','Bài 2: Tổ chức thông tin trong máy tính','Bài 3: Soạn thảo văn bản nâng cao','Bài 4: Bảng tính điện tử','Bài 5: Lập trình kéo thả nâng cao','Bài 6: Dự án số','Bài 7: An toàn và đạo đức trên mạng'],
'Công nghệ':['Bài 1: Lắp ráp mô hình xe chạy bằng năng lượng mặt trời','Bài 2: Cắt khâu túi xách tay','Bài 3: Trồng và chăm sóc cây hoa','Bài 4: Chế biến món ăn đơn giản','Bài 5: Lắp ghép mô hình robot','Bài 6: An toàn lao động'],
'Hoạt động trải nghiệm':['Bài 1: Chân dung tuổi thiếu niên','Bài 2: Mái ấm gia đình','Bài 3: Tự hào truyền thống','Bài 4: Trách nhiệm với cộng đồng','Bài 5: Khám phá nghề nghiệp','Bài 6: Rèn luyện bản thân'],
'Tiếng Anh':['Unit 1: All about me!','Unit 2: Our friends','Unit 3: The food we eat','Unit 4: Our free-time activities','Unit 5: My future job','Unit 6: A visit to the zoo','Unit 7: Our summer holidays','Unit 8: A trip to the country','Unit 9: Our sports day','Unit 10: Our school trip','Unit 11: Family time','Unit 12: At the history museum','Unit 13: Festivals around the world','Unit 14: Health and fitness','Unit 15: The world around us','Unit 16: Life in the future','Unit 17: Protecting our environment','Unit 18: Travel the world','Unit 19: Technology and life','Unit 20: Looking back']
},

'6':{
'Toán':['Bài 1: Tập hợp','Bài 2: Các phép tính với số tự nhiên','Bài 3: Lũy thừa với số mũ tự nhiên','Bài 4: Chia hết và chia có dư','Bài 5: Quan hệ chia hết. Tính chất','Bài 6: Dấu hiệu chia hết cho 2 và cho 5','Bài 7: Dấu hiệu chia hết cho 3 và cho 9','Bài 8: Số nguyên tố. Hợp số','Bài 9: Phân tích một số ra thừa số nguyên tố','Bài 10: Ước chung và bội chung','Bài 11: Số nguyên âm','Bài 12: Tập hợp các số nguyên','Bài 13: Thứ tự trong tập hợp số nguyên','Bài 14: Phép cộng và phép trừ số nguyên','Bài 15: Phép nhân số nguyên','Bài 16: Phép chia hết. Ước và bội của số nguyên','Bài 17: Phân số với tử và mẫu là số nguyên','Bài 18: Phép cộng và phép trừ phân số','Bài 19: Phép nhân và phép chia phân số','Bài 20: Hỗn số. Số thập phân. Phần trăm','Bài 21: Tia số. Điểm và đường thẳng','Bài 22: Ba điểm thẳng hàng','Bài 23: Đoạn thẳng','Bài 24: Trung điểm của đoạn thẳng','Bài 25: Góc','Bài 26: Tia phân giác của góc','Bài 27: Đường tròn','Bài 28: Tam giác'],
'Ngữ văn':['Bài 1: Tôi và các bạn','Bài 2: Gõ cửa trái tim','Bài 3: Yêu thương và chia sẻ','Bài 4: Quê hương yêu dấu','Bài 5: Những nẻo đường xứ sở','Bài 6: Chuyện kể về những người anh hùng','Bài 7: Thế giới cổ tích','Bài 8: Khác biệt và gần gũi','Bài 9: Trái đất – Ngôi nhà chung','Bài 10: Cuốn sách tôi yêu'],
'KHTN':['Bài 1: Giới thiệu về Khoa học tự nhiên','Bài 2: Một số dụng cụ và hóa chất','Bài 3: Quy định an toàn trong phòng thực hành','Bài 4: Đo chiều dài','Bài 5: Đo khối lượng','Bài 6: Đo thời gian','Bài 7: Đo nhiệt độ','Bài 8: Sự đa dạng và phân loại thế giới sống','Bài 9: Tế bào – Đơn vị cơ sở của sự sống','Bài 10: Từ tế bào đến cơ thể','Bài 11: Sự đa dạng của vi khuẩn','Bài 12: Thực vật','Bài 13: Động vật','Bài 14: Nấm','Bài 15: Virus','Bài 16: Lực và tác dụng của lực','Bài 17: Biểu diễn lực','Bài 18: Trọng lực và lực căng','Bài 19: Lực ma sát','Bài 20: Lực cản của nước và không khí','Bài 21: Lực hút của Trái Đất','Bài 22: Năng lượng và cuộc sống','Bài 23: Bảo toàn năng lượng','Bài 24: Năng lượng hao phí','Bài 25: Chất tinh khiết và hỗn hợp','Bài 26: Tách chất ra khỏi hỗn hợp','Bài 27: Oxygen','Bài 28: Không khí và bảo vệ môi trường','Bài 29: Nước','Bài 30: Muối khoáng','Bài 31: Sinh học về đất'],
'Lịch sử và Địa lí':['Bài 1: Lịch sử là gì','Bài 2: Thời gian trong lịch sử','Bài 3: Nguồn gốc loài người','Bài 4: Xã hội nguyên thủy','Bài 5: Sự chuyển biến và phân hóa của xã hội nguyên thủy','Bài 6: Ai Cập và Lưỡng Hà cổ đại','Bài 7: Ấn Độ cổ đại','Bài 8: Trung Quốc từ thời cổ đại đến thế kỉ VII','Bài 9: Hi Lạp và La Mã cổ đại','Bài 10: Các quốc gia sơ kì ở Đông Nam Á','Bài 11: Vị trí địa lí và phạm vi của biển','Bài 12: Thạch quyển – Nội lực','Bài 13: Ngoại lực','Bài 14: Khí quyển của Trái Đất','Bài 15: Thời tiết và khí hậu','Bài 16: Nước trên Trái Đất','Bài 17: Biển và đại dương','Bài 18: Đất và sinh vật trên Trái Đất','Bài 19: Con người và thiên nhiên'],
'GDCD':['Bài 1: Tự hào về truyền thống dân tộc Việt Nam','Bài 2: Tôn trọng sự thật','Bài 3: Yêu thương con người','Bài 4: Tôn trọng sự đa dạng của các dân tộc','Bài 5: Bảo tồn di sản văn hóa','Bài 6: Tự lập','Bài 7: Ứng phó với các tình huống nguy hiểm','Bài 8: Tiết kiệm','Bài 9: Công dân nước Cộng hòa xã hội chủ nghĩa Việt Nam','Bài 10: Quyền và nghĩa vụ cơ bản của công dân'],
'Tin học':['Bài 1: Thông tin và xử lí thông tin','Bài 2: Em và các bạn cùng khám phá không gian số','Bài 3: Tổ chức thông tin trong máy tính','Bài 4: Sử dụng phần mềm trình chiếu','Bài 5: Định dạng văn bản','Bài 6: Chèn hình ảnh vào văn bản','Bài 7: Bảng tính điện tử','Bài 8: Sử dụng hàm trong bảng tính','Bài 9: Internet và dịch vụ internet','Bài 10: An toàn trên không gian mạng'],
'Công nghệ':['Bài 1: Nhà ở đối với con người','Bài 2: Xây dựng nhà ở','Bài 3: Ngôi nhà thông minh','Bài 4: Thực phẩm và dinh dưỡng','Bài 5: Phương pháp bảo quản và chế biến thực phẩm','Bài 6: Dự án: Bữa ăn kết nối yêu thương','Bài 7: Trang phục trong đời sống','Bài 8: Lựa chọn và sử dụng trang phục','Bài 9: Thời trang','Bài 10: Đồ dùng điện trong gia đình','Bài 11: Mạng điện trong nhà'],
'Âm nhạc':['Chủ đề 1: Tuổi học trò','Chủ đề 2: Bài ca hòa bình','Chủ đề 3: Nhớ ơn thầy cô','Chủ đề 4: Khúc hát quê hương','Chủ đề 5: Mùa xuân','Chủ đề 6: Giai điệu bạn bè','Chủ đề 7: Âm nhạc nước ngoài','Chủ đề 8: Bác Hồ kính yêu'],
'Mĩ thuật':['Chủ đề 1: Biểu cảm của sắc màu','Chủ đề 2: Nghệ thuật tiền sử và cổ đại','Chủ đề 3: Lễ hội quê hương','Chủ đề 4: Nghệ thuật trung đại Việt Nam','Chủ đề 5: Thiết kế tạo dáng','Chủ đề 6: Nghệ thuật hiện đại thế giới'],
'Hoạt động trải nghiệm':['Chủ đề 1: Khám phá bản thân','Chủ đề 2: Rèn luyện sự tự tin','Chủ đề 3: Xây dựng tình bạn','Chủ đề 4: Tri ân thầy cô','Chủ đề 5: Gia đình yêu thương','Chủ đề 6: Tham gia hoạt động cộng đồng','Chủ đề 7: Tìm hiểu nghề nghiệp','Chủ đề 8: Phòng tránh thiên tai'],
'Tiếng Anh':['Unit 1: My new school','Unit 2: My house','Unit 3: My friends','Unit 4: My neighbourhood','Unit 5: Natural wonders of Viet Nam','Unit 6: Our Tet holiday','Unit 7: Television','Unit 8: Sports and games','Unit 9: Cities of the world','Unit 10: Our houses in the future','Unit 11: Our greener world','Unit 12: Robots']
},
'7':{
'Toán':['Bài 1: Tập hợp Q các số hữu tỉ','Bài 2: Cộng, trừ, nhân, chia số hữu tỉ','Bài 3: Lũy thừa của một số hữu tỉ','Bài 4: Thứ tự thực hiện các phép tính. Quy tắc chuyển vế','Bài 5: Làm quen với số thập phân vô hạn tuần hoàn','Bài 6: Số vô tỉ. Căn bậc hai số học','Bài 7: Tập hợp các số thực','Bài 8: Góc ở vị trí đặc biệt. Tia phân giác của một góc','Bài 9: Hai đường thẳng song song và dấu hiệu nhận biết','Bài 10: Tiên đề Euclid. Tính chất của hai đường thẳng song song','Bài 11: Định lí và chứng minh định lí','Bài 12: Tổng các góc của một tam giác','Bài 13: Hai tam giác bằng nhau. Trường hợp bằng nhau thứ nhất của tam giác','Bài 14: Trường hợp bằng nhau thứ hai và thứ ba của tam giác','Bài 15: Các trường hợp bằng nhau của tam giác vuông','Bài 16: Tam giác cân. Đường trung trực của đoạn thẳng','Bài 17: Thu thập và phân loại dữ liệu','Bài 18: Biểu đồ hình quạt tròn','Bài 19: Biểu đồ đoạn thẳng','Bài 20: Tỉ lệ thức','Bài 21: Tính chất của dãy tỉ số bằng nhau','Bài 22: Đại lượng tỉ lệ thuận','Bài 23: Đại lượng tỉ lệ nghịch','Bài 24: Biểu thức đại số','Bài 25: Đa thức một biến','Bài 26: Phép cộng và phép trừ đa thức một biến','Bài 27: Phép nhân đa thức một biến','Bài 28: Phép chia đa thức một biến','Bài 29: Làm quen với biến cố','Bài 30: Làm quen với xác suất của biến cố','Bài 31: Quan hệ giữa góc và cạnh đối diện trong một tam giác','Bài 32: Quan hệ giữa đường vuông góc và đường xiên','Bài 33: Quan hệ giữa ba cạnh của một tam giác','Bài 34: Sự đồng quy của ba đường trung tuyến, ba đường phân giác trong một tam giác','Bài 35: Sự đồng quy của ba đường trung trực, ba đường cao trong một tam giác','Bài 36: Hình hộp chữ nhật và hình lập phương','Bài 37: Hình lăng trụ đứng tam giác và hình lăng trụ đứng tứ giác'],
'Ngữ văn':['Bài 1: Bầu trời tuổi thơ','Bài 2: Khúc nhạc tâm hồn','Bài 3: Cội nguồn yêu thương','Bài 4: Giai điệu đất nước','Bài 5: Màu sắc trăm miền','Bài 6: Bài học cuộc sống','Bài 7: Thế giới viễn tưởng','Bài 8: Trải nghiệm để trưởng thành','Bài 9: Hòa điệu với tự nhiên','Bài 10: Sách và văn hóa đọc'],
'KHTN':['Bài 1: Phương pháp và kĩ năng học tập môn KHTN','Bài 2: Nguyên tử','Bài 3: Nguyên tố hóa học','Bài 4: Sơ lược về bảng tuần hoàn các nguyên tố hóa học','Bài 5: Phân tử','Bài 6: Giới thiệu về liên kết hóa học','Bài 7: Hóa trị','Bài 8: Công thức hóa học','Bài 9: Tốc độ','Bài 10: Đồ thị quãng đường – thời gian','Bài 11: Gia tốc và chuyển động có gia tốc','Bài 12: Lực và chuyển động','Bài 13: Lực hấp dẫn','Bài 14: Áp suất','Bài 15: Áp suất chất lỏng và chất khí','Bài 16: Trao đổi khí ở sinh vật','Bài 17: Vai trò của trao đổi chất và chuyển hóa năng lượng','Bài 18: Quang hợp ở thực vật','Bài 19: Một số yếu tố ảnh hưởng đến quang hợp','Bài 20: Hô hấp tế bào','Bài 21: Sinh trưởng và phát triển ở sinh vật','Bài 22: Sinh sản ở sinh vật','Bài 23: Sinh sản vô tính ở sinh vật','Bài 24: Sinh sản hữu tính ở sinh vật','Bài 25: Cơ thể sinh vật là một thể thống nhất'],
'Lịch sử và Địa lí':['Bài 1: Quá trình hình thành và phát triển chế độ phong kiến Tây Âu','Bài 2: Các cuộc phát kiến địa lí','Bài 3: Phong trào văn hóa Phục hưng và Cải cách tôn giáo','Bài 4: Trung Quốc từ thế kỉ VII đến giữa thế kỉ XIX','Bài 5: Ấn Độ từ thế kỉ IV đến giữa thế kỉ XIX','Bài 6: Vương quốc Cam-pu-chia và Vương quốc Lào','Bài 7: Các quốc gia phong kiến Đông Nam Á','Bài 8: Châu Âu','Bài 9: Châu Á','Bài 10: Châu Phi','Bài 11: Châu Mỹ','Bài 12: Châu Đại Dương','Bài 13: Châu Nam Cực','Bài 14: Nước Đại Việt thời Đinh - Tiền Lê','Bài 15: Nước Đại Việt thời Lý','Bài 16: Nước Đại Việt thời Trần','Bài 17: Nước Đại Việt thời Lê sơ'],
'GDCD':['Bài 1: Tự hào về truyền thống quê hương','Bài 2: Bảo tồn di sản văn hóa','Bài 3: Quan tâm, cảm thông và chia sẻ','Bài 4: Học tập tự giác, tích cực','Bài 5: Giữ chữ tín','Bài 6: Quản lí tiền','Bài 7: Ứng phó với tâm lí căng thẳng','Bài 8: Phòng, chống bạo lực học đường','Bài 9: Quản lí thời gian','Bài 10: Quyền và nghĩa vụ của công dân trong gia đình'],
'Tin học':['Bài 1: Thiết bị vào - ra','Bài 2: Phần mềm máy tính','Bài 3: Quản lí dữ liệu trong máy tính','Bài 4: Mạng xã hội và một số kênh trao đổi thông tin trên internet','Bài 5: Văn hóa học ứng xử qua mạng','Bài 6: Định dạng trang tính','Bài 7: Sử dụng địa chỉ ô tính trong công thức','Bài 8: Sắp xếp và lọc dữ liệu','Bài 9: Trình bày dữ liệu bằng biểu đồ','Bài 10: Cấu trúc tuần tự, rẽ nhánh và lặp'],
'Công nghệ':['Bài 1: Nhập môn trồng trọt','Bài 2: Làm đất trồng cây','Bài 3: Gieo trồng, chăm sóc và phòng trừ sâu, bệnh cho cây trồng','Bài 4: Thu hoạch sản phẩm trồng trọt','Bài 5: Nhân giống vô tính cây trồng','Bài 6: Dự án trồng rau an toàn','Bài 7: Giới thiệu về lâm nghiệp','Bài 8: Trồng, chăm sóc và bảo vệ rừng','Bài 9: Giới thiệu về chăn nuôi','Bài 10: Nuôi dưỡng và chăm sóc vật nuôi','Bài 11: Nuôi trồng thủy sản'],
'Âm nhạc':['Chủ đề 1: Tiếng hát mùa thu','Chủ đề 2: Khúc hát quê hương','Chủ đề 3: Bài ca người giáo viên','Chủ đề 4: Tình bạn','Chủ đề 5: Giai điệu mùa xuân','Chủ đề 6: Âm nhạc nước ngoài','Chủ đề 7: Khúc hát đồng dao','Chủ đề 8: Chào mùa hè'],
'Mĩ thuật':['Chủ đề 1: Mĩ thuật thời kì Trung đại','Chủ đề 2: Nghệ thuật tạo hình Việt Nam','Chủ đề 3: Thiết kế tạo dáng công nghiệp','Chủ đề 4: Thiết kế thời trang','Chủ đề 5: Nghệ thuật trang trí','Chủ đề 6: Nghệ thuật điêu khắc'],
'Hoạt động trải nghiệm':['Chủ đề 1: Khám phá trường THCS','Chủ đề 2: Quản lí bản thân','Chủ đề 3: Hợp tác với bạn bè','Chủ đề 4: Ứng xử trong gia đình','Chủ đề 5: Tham gia hoạt động thiện nguyện','Chủ đề 6: Phát triển tài năng','Chủ đề 7: Nghề nghiệp tương lai','Chủ đề 8: Bảo vệ thiên nhiên'],
'Tiếng Anh':['Unit 1: Hobbies','Unit 2: Healthy living','Unit 3: Community service','Unit 4: Music and arts','Unit 5: Food and drink','Unit 6: A visit to a school','Unit 7: Traffic','Unit 8: Films','Unit 9: Festivals around the world','Unit 10: Energy sources','Unit 11: Travelling in the future','Unit 12: English-speaking countries']
},
'8':{
'Toán':['Bài 1: Đơn thức','Bài 2: Đa thức','Bài 3: Phép cộng và phép trừ đa thức','Bài 4: Phép nhân đa thức','Bài 5: Phép chia đa thức cho đơn thức','Bài 6: Hiệu hai bình phương. Bình phương của một tổng hay một hiệu','Bài 7: Lập phương của một tổng hay một hiệu','Bài 8: Tổng và hiệu hai lập phương','Bài 9: Phân tích đa thức thành nhân tử','Bài 10: Tứ giác','Bài 11: Hình thang cân','Bài 12: Hình bình hành','Bài 13: Hình chữ nhật','Bài 14: Hình thoi và hình vuông','Bài 15: Định lí Thalès trong tam giác','Bài 16: Đường trung bình của tam giác','Bài 17: Tính chất đường phân giác của tam giác','Bài 18: Thu thập và phân loại dữ liệu','Bài 19: Biểu diễn dữ liệu bằng bảng, biểu đồ','Bài 20: Phân tích số liệu thống kê dựa vào biểu đồ','Bài 21: Phân thức đại số','Bài 22: Tính chất cơ bản của phân thức đại số','Bài 23: Phép cộng và phép trừ phân thức đại số','Bài 24: Phép nhân và phép chia phân thức đại số','Bài 25: Phương trình bậc nhất một ẩn','Bài 26: Giải bài toán bằng cách lập phương trình','Bài 27: Khái niệm hàm số và đồ thị của hàm số','Bài 28: Hàm số bậc nhất và đồ thị của hàm số bậc nhất','Bài 29: Hệ số góc của đường thẳng','Bài 30: Kết quả có thể và kết quả thuận lợi','Bài 31: Cách tính xác suất của biến cố bằng tỉ số','Bài 32: Mối liên hệ giữa xác suất thực nghiệm với xác suất và ứng dụng','Bài 33: Hai tam giác đồng dạng','Bài 34: Ba trường hợp đồng dạng của hai tam giác','Bài 35: Định lí Pythagoras và ứng dụng','Bài 36: Các trường hợp đồng dạng của hai tam giác vuông','Bài 37: Hình chóp tam giác đều và hình chóp tứ giác đều','Bài 38: Diện tích xung quanh và thể tích của hình chóp tam giác đều','Bài 39: Diện tích xung quanh và thể tích của hình chóp tứ giác đều'],
'Ngữ văn':['Bài 1: Câu chuyện của lịch sử','Bài 2: Vẻ đẹp cổ điển','Bài 3: Lời sông núi','Bài 4: Tiếng cười trào phúng','Bài 5: Những cảnh đời éo le','Bài 6: Chân dung cuộc sống','Bài 7: Tin và truyện tin','Bài 8: Cánh cửa mở ra thế giới','Bài 9: Hành trình tri thức','Bài 10: Sách và cuộc sống'],
'KHTN':['Bài 1: Sử dụng một số hóa chất và thiết bị trong phòng thực hành','Bài 2: Biến đổi vật lí và biến đổi hóa học','Bài 3: Phản ứng hóa học','Bài 4: Mol và tỉ khối của chất khí','Bài 5: Dung dịch và nồng độ dung dịch','Bài 6: Acid','Bài 7: Base. Thang pH','Bài 8: Oxide','Bài 9: Muối và phân bón hóa học','Bài 10: Mạch điện đơn giản','Bài 11: Tác dụng của dòng điện','Bài 12: Đo cường độ dòng điện và hiệu điện thế','Bài 13: Điện trở. Định luật Ohm','Bài 14: Đoạn mạch nối tiếp, song song','Bài 15: Tác dụng từ của dòng điện. Từ trường','Bài 16: Từ trường Trái Đất. Sử dụng la bàn','Bài 17: Sử dụng điện an toàn và tiết kiệm','Bài 18: Nhiệt năng và nội năng','Bài 19: Dẫn nhiệt','Bài 20: Đối lưu và bức xạ nhiệt','Bài 21: Công thức tính nhiệt lượng','Bài 22: Sự nở vì nhiệt','Bài 23: Sự chuyển thể của chất','Bài 24: Đặc điểm và ứng dụng của nhiệt kế','Bài 25: Năng lượng nhiệt trong thực tiễn','Bài 26: Năng lượng tái tạo','Bài 27: Thực hành đo năng lượng nhiệt bằng joulemeter','Bài 28: Hệ vận động ở người','Bài 29: Dinh dưỡng và tiêu hóa ở người','Bài 30: Máu và hệ tuần hoàn của người','Bài 31: Hô hấp ở người','Bài 32: Hệ bài tiết ở người','Bài 33: Thần kinh và giác quan','Bài 34: Da và điều hòa thân nhiệt','Bài 35: Sinh sản ở người','Bài 36: Sinh thái học và môi trường','Bài 37: Quần thể sinh vật','Bài 38: Quần xã sinh vật','Bài 39: Hệ sinh thái','Bài 40: Sinh quyển','Bài 41: Bảo vệ môi trường'],
'Lịch sử và Địa lí':['Bài 1: Cách mạng tư sản Anh và Chiến tranh giành độc lập của các thuộc địa Anh ở Bắc Mỹ','Bài 2: Cách mạng tư sản Pháp','Bài 3: Cách mạng công nghiệp','Bài 4: Đông Nam Á từ nửa sau thế kỉ XVI đến giữa thế kỉ XIX','Bài 5: Xung đột Nam - Bắc triều và Trịnh - Nguyễn','Bài 6: Công cuộc khai phá vùng đất phía Nam từ thế kỉ XVI đến thế kỉ XVIII','Bài 7: Khởi nghĩa nông dân ở Đàng Ngoài thế kỉ XVIII','Bài 8: Phong trào Tây Sơn','Bài 9: Nước Đại Việt thời Tây Sơn','Bài 10: Nước Việt Nam thời Nguyễn','Bài 11: Chủ nghĩa tư bản thế kỉ XIX','Bài 12: Sự phát triển của khoa học kĩ thuật thế kỉ XVIII-XIX','Bài 13: Trung Quốc và Nhật Bản thế kỉ XIX','Bài 14: Ấn Độ và Đông Nam Á thế kỉ XIX','Bài 15: Vị trí địa lí, địa hình và khoáng sản Việt Nam','Bài 16: Khí hậu và thủy văn Việt Nam','Bài 17: Thổ nhưỡng và sinh vật Việt Nam','Bài 18: Biển đảo Việt Nam','Bài 19: Dân cư và lao động Việt Nam'],
'GDCD':['Bài 1: Tự hào về truyền thống dân tộc Việt Nam','Bài 2: Tôn trọng sự đa dạng của các dân tộc','Bài 3: Lao động cần cù, sáng tạo','Bài 4: Bảo vệ lẽ phải','Bài 5: Bảo vệ môi trường và tài nguyên thiên nhiên','Bài 6: Xác định mục tiêu cá nhân','Bài 7: Phòng, chống bạo lực gia đình','Bài 8: Lập kế hoạch chi tiêu','Bài 9: Phòng ngừa tai nạn vũ khí, cháy, nổ và các chất độc hại','Bài 10: Quyền và nghĩa vụ lao động của công dân'],
'Tin học':['Bài 1: Lược sử công cụ tính toán','Bài 2: Thông tin trong môi trường số','Bài 3: Thực hành: Khai thác thông tin số','Bài 4: Đạo đức và văn hóa trong sử dụng công nghệ kĩ thuật số','Bài 5: Sử dụng địa chỉ tương đối, tuyệt đối trong công thức','Bài 6: Sắp xếp và lọc dữ liệu','Bài 7: Trực quan hóa dữ liệu','Bài 8: Xử lí ảnh','Bài 9: Thực hành: Tạo video ngắn','Bài 10: Lập trình với Scratch','Bài 11: Cấu trúc rẽ nhánh trong Scratch','Bài 12: Cấu trúc lặp trong Scratch','Bài 13: Tin học và nghề nghiệp'],
'Công nghệ':['Bài 1: Tiêu chuẩn trình bày bản vẽ kĩ thuật','Bài 2: Hình chiếu vuông góc','Bài 3: Bản vẽ chi tiết','Bài 4: Bản vẽ lắp','Bài 5: Bản vẽ nhà','Bài 6: Vật liệu cơ khí','Bài 7: Các phương pháp gia công cơ khí','Bài 8: Chi tiết máy và lắp ghép','Bài 9: Truyền chuyển động','Bài 10: Mạch điện điều khiển','Bài 11: Lắp ráp mạch điện điều khiển','Bài 12: Ngành nghề cơ khí và kĩ thuật điện'],
'Âm nhạc':['Chủ đề 1: Giai điệu tự hào','Chủ đề 2: Việt Nam quê hương tôi','Chủ đề 3: Vui bước đến trường','Chủ đề 4: Âm nhạc nước ngoài','Chủ đề 5: Mùa xuân gọi','Chủ đề 6: Khúc ca tình bạn','Chủ đề 7: Nhạc cụ dân tộc','Chủ đề 8: Giai điệu mùa hè'],
'Mĩ thuật':['Chủ đề 1: Hình ảnh con người trong mĩ thuật','Chủ đề 2: Nghệ thuật hiện đại Việt Nam','Chủ đề 3: Thiết kế logo','Chủ đề 4: Thiết kế bao bì','Chủ đề 5: Nghệ thuật đương đại','Chủ đề 6: Nghệ thuật công cộng'],
'Hoạt động trải nghiệm':['Chủ đề 1: Khám phá điểm mạnh, điểm yếu của bản thân','Chủ đề 2: Kĩ năng giao tiếp và ứng xử','Chủ đề 3: Xây dựng kế hoạch tài chính cá nhân','Chủ đề 4: Tham gia các hoạt động xã hội','Chủ đề 5: Hướng nghiệp và tương lai','Chủ đề 6: Bảo tồn di sản văn hóa','Chủ đề 7: Tình yêu quê hương, đất nước','Chủ đề 8: Đối phó với áp lực học tập'],
'Tiếng Anh':['Unit 1: Leisure time','Unit 2: Life in the countryside','Unit 3: Teenagers','Unit 4: Ethnic groups of Viet Nam','Unit 5: Our customs and traditions','Unit 6: Lifestyles','Unit 7: Environmental protection','Unit 8: Shopping','Unit 9: Natural disasters','Unit 10: Communication in the future','Unit 11: Science and technology','Unit 12: Life on other planets']
},
'9':{
'Toán':['Bài 1: Phương trình bậc nhất hai ẩn','Bài 2: Hệ hai phương trình bậc nhất hai ẩn','Bài 3: Giải bài toán bằng cách lập hệ phương trình','Bài 4: Phương trình quy về phương trình bậc nhất một ẩn','Bài 5: Bất đẳng thức','Bài 6: Bất phương trình bậc nhất một ẩn','Bài 7: Căn bậc hai và căn thức bậc hai','Bài 8: Biến đổi đơn giản biểu thức chứa căn thức bậc hai','Bài 9: Căn bậc ba và căn thức bậc ba','Bài 10: Tỉ số lượng giác của góc nhọn','Bài 11: Một số hệ thức giữa cạnh, góc trong tam giác vuông','Bài 12: Ứng dụng của tỉ số lượng giác của góc nhọn','Bài 13: Đường tròn','Bài 14: Vị trí tương đối của hai đường tròn','Bài 15: Vị trí tương đối của đường thẳng và đường tròn','Bài 16: Góc ở tâm, số đo cung, cung chứa góc','Bài 17: Góc nội tiếp','Bài 18: Đường tròn ngoại tiếp và nội tiếp','Bài 19: Đa giác đều','Bài 20: Độ dài đường tròn, cung tròn','Bài 21: Diện tích hình tròn, hình quạt tròn','Bài 22: Hình trụ','Bài 23: Hình nón','Bài 24: Hình cầu','Bài 25: Hàm số y=ax^2 (a khác 0)','Bài 26: Phương trình bậc hai một ẩn','Bài 27: Định lí Viète','Bài 28: Giải bài toán bằng cách lập phương trình bậc hai','Bài 29: Tần số. Tần số tương đối','Bài 30: Biểu đồ tần số tương đối','Bài 31: Phép thử ngẫu nhiên và không gian mẫu','Bài 32: Xác suất của biến cố'],
'Ngữ văn':['Bài 1: Thế giới kì ảo','Bài 2: Những cung bậc tâm trạng','Bài 3: Hồn nước tình quê','Bài 4: Khám phá vẻ đẹp văn chương','Bài 5: Đối diện với nỗi đau','Bài 6: Tìm hiểu thế giới tự nhiên','Bài 7: Âm vang của lịch sử','Bài 8: Những vấn đề toàn cầu','Bài 9: Cuộc sống qua lăng kính','Bài 10: Văn học và cuộc đời'],
'KHTN':['Bài 1: Nhận biết một số dụng cụ, hóa chất','Bài 2: Động năng. Thế năng','Bài 3: Cơ năng','Bài 4: Khúc xạ ánh sáng','Bài 5: Hiện tượng tán sắc ánh sáng','Bài 6: Thấu kính','Bài 7: Kính lúp. Mắt. Máy ảnh','Bài 8: Điện trở. Định luật Ohm','Bài 9: Đoạn mạch nối tiếp, song song','Bài 10: Năng lượng điện. Công suất điện','Bài 11: Hiện tượng cảm ứng điện từ','Bài 12: Dòng điện xoay chiều','Bài 13: Tính chất hóa học của kim loại','Bài 14: Dãy hoạt động hóa học của kim loại','Bài 15: Tách kim loại','Bài 16: Hợp kim','Bài 17: Sự ăn mòn kim loại','Bài 18: Tính chất hóa học của phi kim','Bài 19: Chlorine','Bài 20: Carbon','Bài 21: Hợp chất hữu cơ','Bài 22: Alkane','Bài 23: Alkene','Bài 24: Ethylic alcohol','Bài 25: Acetic acid','Bài 26: Lipid','Bài 27: Carbohydrate','Bài 28: Protein. Polymer','Bài 29: Di truyền học Mendel','Bài 30: Nhiễm sắc thể','Bài 31: DNA và RNA','Bài 32: Đột biến gene và đột biến nhiễm sắc thể','Bài 33: Di truyền học người','Bài 34: Ứng dụng di truyền học','Bài 35: Tiến hóa học','Bài 36: Nguồn gốc sự sống'],
'Lịch sử và Địa lí':['Bài 1: Nước Nga và Liên Xô (1918-1945)','Bài 2: Châu Âu và nước Mỹ (1918-1945)','Bài 3: Châu Á từ 1918 đến 1945','Bài 4: Phong trào giải phóng dân tộc (1918-1945)','Bài 5: Chiến tranh thế giới thứ hai','Bài 6: Việt Nam từ 1919 đến 1930','Bài 7: Đảng Cộng sản Việt Nam ra đời','Bài 8: Cao trào cách mạng tiến tới Tổng khởi nghĩa','Bài 9: Cách mạng tháng Tám năm 1945','Bài 10: Nước Việt Nam Dân chủ Cộng hòa','Bài 11: Địa lí dân cư Việt Nam','Bài 12: Địa lí các ngành kinh tế Việt Nam','Bài 13: Nông nghiệp, lâm nghiệp, thủy sản','Bài 14: Công nghiệp Việt Nam','Bài 15: Dịch vụ Việt Nam','Bài 16: Các vùng kinh tế Việt Nam','Bài 17: Phát triển tổng hợp kinh tế và bảo vệ môi trường biển đảo'],
'GDCD':['Bài 1: Sống có lí tưởng','Bài 2: Khoan dung','Bài 3: Làm việc có kế hoạch','Bài 4: Bảo vệ hòa bình','Bài 5: Tình hữu nghị giữa các dân tộc trên thế giới','Bài 6: Hợp tác cùng phát triển','Bài 7: Quyền và nghĩa vụ công dân trong hôn nhân','Bài 8: Quyền và nghĩa vụ công dân về kinh doanh và thuế','Bài 9: Vi phạm pháp luật và trách nhiệm pháp lí','Bài 10: Quyền tham gia quản lí nhà nước và xã hội'],
'Tin học':['Bài 1: Mạng máy tính và internet','Bài 2: Sử dụng công cụ tìm kiếm trên internet','Bài 3: Thư điện tử','Bài 4: Tạo trang web đơn giản','Bài 5: Đạo đức, pháp luật và văn hóa trong môi trường số','Bài 6: Bảo vệ thông tin máy tính','Bài 7: Trình bày thông tin đa phương tiện','Bài 8: Thực hành trình bày thông tin đa phương tiện','Bài 9: Bài toán và thuật toán','Bài 10: Lập trình giải bài toán bằng Python','Bài 11: Cấu trúc rẽ nhánh trong Python','Bài 12: Cấu trúc lặp trong Python','Bài 13: Tin học và phát triển kinh tế'],
'Công nghệ':['Bài 1: Nghề nghiệp trong lĩnh vực kĩ thuật, công nghệ','Bài 2: Lựa chọn nghề nghiệp','Bài 3: Hệ thống kĩ thuật','Bài 4: Thiết kế kĩ thuật','Bài 5: Vẽ kĩ thuật bằng máy tính','Bài 6: Quy trình thiết kế kĩ thuật','Bài 7: Lắp ráp mạch điện tử đơn giản','Bài 8: Công nghệ mới','Bài 9: Tự động hóa','Bài 10: Robot công nghiệp','Bài 11: Dự án thiết kế sản phẩm kĩ thuật'],
'Âm nhạc':['Chủ đề 1: Giai điệu mùa thu','Chủ đề 2: Tình ca quê hương','Chủ đề 3: Khúc hát tri ân','Chủ đề 4: Âm nhạc thế giới','Chủ đề 5: Nhịp điệu tuổi trẻ','Chủ đề 6: Bài ca tình bạn','Chủ đề 7: Nhạc kịch','Chủ đề 8: Khúc ca tạm biệt'],
'Mĩ thuật':['Chủ đề 1: Nghệ thuật thiết kế','Chủ đề 2: Mĩ thuật đương đại','Chủ đề 3: Nghệ thuật truyện tranh','Chủ đề 4: Nghệ thuật đồ họa','Chủ đề 5: Nghệ thuật điện ảnh','Chủ đề 6: Nghệ thuật trình diễn'],
'Hoạt động trải nghiệm':['Chủ đề 1: Lập kế hoạch học tập, rèn luyện','Chủ đề 2: Quản lí cảm xúc, ứng phó với căng thẳng','Chủ đề 3: Kĩ năng thuyết phục, thương lượng','Chủ đề 4: Xây dựng truyền thống nhà trường','Chủ đề 5: Phát huy truyền thống gia đình','Chủ đề 6: Hoạt động vì cộng đồng','Chủ đề 7: Tìm hiểu hệ thống đào tạo nghề','Chủ đề 8: Lựa chọn hướng đi sau THCS'],
'Tiếng Anh':['Unit 1: Local environment','Unit 2: City life','Unit 3: Healthy living for teens','Unit 4: Remembering the past','Unit 5: Wonders of Viet Nam','Unit 6: Viet Nam: Then and now','Unit 7: Natural wonders of the world','Unit 8: Tourism','Unit 9: English in the world','Unit 10: Planet Earth','Unit 11: Electronic devices','Unit 12: Career choices']
},
'10':{
'Toán':['Bài 1: Mệnh đề','Bài 2: Tập hợp và các phép toán trên tập hợp','Bài 3: Bất phương trình và hệ bất phương trình bậc nhất hai ẩn','Bài 4: Hệ thức lượng trong tam giác','Bài 5: Vectơ','Bài 6: Tổng và hiệu của hai vectơ','Bài 7: Tích của một số với một vectơ','Bài 8: Tích vô hướng của hai vectơ','Bài 9: Số gần đúng. Sai số','Bài 10: Các số đặc trưng đo xu thế trung tâm của mẫu số liệu không ghép nhóm','Bài 11: Các số đặc trưng đo mức độ phân tán của mẫu số liệu không ghép nhóm','Bài 12: Hàm số, đồ thị và ứng dụng','Bài 13: Hàm số bậc hai','Bài 14: Dấu của tam thức bậc hai','Bài 15: Phương trình quy về phương trình bậc hai','Bài 16: Tọa độ của vectơ','Bài 17: Biểu thức tọa độ của các phép toán vectơ','Bài 18: Phương trình đường thẳng','Bài 19: Vị trí tương đối, góc, khoảng cách','Bài 20: Phương trình đường tròn','Bài 21: Ba đường conic','Bài 22: Quy tắc đếm','Bài 23: Hoán vị, chỉnh hợp và tổ hợp','Bài 24: Nhị thức Newton','Bài 25: Biến cố và định nghĩa cổ điển của xác suất','Bài 26: Thực hành tính xác suất'],
'Ngữ văn':['Bài 1: Sức hấp dẫn của truyện kể','Bài 2: Vẻ đẹp của thơ ca','Bài 3: Nghệ thuật thuyết phục trong văn nghị luận','Bài 4: Sức sống của sử thi','Bài 5: Tích trò sân khấu dân gian','Bài 6: Nguyễn Trãi – Cuộc đời và sự nghiệp','Bài 7: Quyền năng của người kể chuyện','Bài 8: Thế giới đa dạng của thông tin','Bài 9: Hành trang cuộc sống','Bài 10: Ôn tập'],
'Tiếng Anh':['Unit 1: Family life','Unit 2: Humans and the environment','Unit 3: Music','Unit 4: For a better community','Unit 5: Inventions','Unit 6: Gender equality','Unit 7: Viet Nam and international organisations','Unit 8: New ways to learn','Unit 9: Protecting the environment','Unit 10: Ecotourism'],
'Vật lí':['Bài 1: Làm quen với Vật lí','Bài 2: Các quy tắc an toàn trong phòng thực hành','Bài 3: Thực hành tính sai số','Bài 4: Động học','Bài 5: Tốc độ và vận tốc','Bài 6: Thực hành đo tốc độ','Bài 7: Đồ thị độ dịch chuyển - thời gian','Bài 8: Chuyển động biến đổi. Gia tốc','Bài 9: Chuyển động thẳng biến đổi đều','Bài 10: Rơi tự do','Bài 11: Thực hành đo gia tốc rơi tự do','Bài 12: Chuyển động ném','Bài 13: Tổng hợp và phân tích lực','Bài 14: Định luật 1 Newton','Bài 15: Định luật 2 Newton','Bài 16: Định luật 3 Newton','Bài 17: Trọng lực và lực căng','Bài 18: Lực ma sát','Bài 19: Lực cản và lực nâng','Bài 20: Momen lực','Bài 21: Năng lượng và công','Bài 22: Công suất','Bài 23: Động năng và thế năng','Bài 24: Cơ năng','Bài 25: Động lượng và định luật bảo toàn động lượng','Bài 26: Chuyển động tròn','Bài 27: Lực hướng tâm','Bài 28: Sự biến dạng','Bài 29: Khối lượng riêng. Áp suất'],
'Hóa học':['Bài 1: Thành phần của nguyên tử','Bài 2: Nguyên tố hóa học','Bài 3: Cấu trúc lớp vỏ electron nguyên tử','Bài 4: Ôn tập chương 1','Bài 5: Cấu tạo bảng tuần hoàn các nguyên tố hóa học','Bài 6: Xu hướng biến đổi tính chất các nguyên tố','Bài 7: Định luật tuần hoàn','Bài 8: Quy tắc octet','Bài 9: Liên kết ion','Bài 10: Liên kết cộng hóa trị','Bài 11: Liên kết hydrogen và tương tác van der Waals','Bài 12: Phản ứng oxi hóa - khử','Bài 13: Năng lượng hóa học','Bài 14: Tốc độ phản ứng hóa học','Bài 15: Nguyên tố nhóm VIIA','Bài 16: Nguyên tố nhóm VIA','Bài 17: Ôn tập cuối năm'],
'Sinh học':['Bài 1: Giới thiệu khái quát môn Sinh học','Bài 2: Các phương pháp nghiên cứu và học tập môn Sinh học','Bài 3: Các cấp độ tổ chức của thế giới sống','Bài 4: Các nguyên tố hóa học và nước','Bài 5: Các phân tử sinh học','Bài 6: Tế bào nhân sơ','Bài 7: Tế bào nhân thực','Bài 8: Vận chuyển các chất qua màng sinh chất','Bài 9: Thực hành quan sát tế bào','Bài 10: Sự chuyển hóa năng lượng và enzyme','Bài 11: Hô hấp tế bào','Bài 12: Quang hợp','Bài 13: Chu kì tế bào và nguyên phân','Bài 14: Giảm phân','Bài 15: Thực hành quan sát quá trình phân bào','Bài 16: Công nghệ tế bào','Bài 17: Đa dạng vi sinh vật','Bài 18: Sinh trưởng và sinh sản ở vi sinh vật','Bài 19: Quá trình tổng hợp, phân giải ở vi sinh vật','Bài 20: Ứng dụng công nghệ vi sinh vật','Bài 21: Khái quát về virus','Bài 22: Vai trò và ứng dụng của virus'],
'Lịch sử':['Bài 1: Hiện thực lịch sử và nhận thức lịch sử','Bài 2: Tri thức lịch sử và cuộc sống','Bài 3: Sử học với các lĩnh vực khoa học khác','Bài 4: Sử học với bảo tồn di sản','Bài 5: Khái quát lịch sử văn minh thế giới','Bài 6: Văn minh phương Đông cổ-trung đại','Bài 7: Văn minh phương Tây cổ-trung đại','Bài 8: Các cuộc cách mạng công nghiệp thời kì cận đại','Bài 9: Các cuộc cách mạng công nghiệp thời kì hiện đại','Bài 10: Cơ sở hình thành văn minh Đông Nam Á','Bài 11: Hành trình phát triển văn minh Đông Nam Á','Bài 12: Văn minh Văn Lang - Âu Lạc','Bài 13: Văn minh Chăm-pa, văn minh Phù Nam','Bài 14: Văn minh Đại Việt','Bài 15: Khối đại đoàn kết dân tộc Việt Nam'],
'Địa lí':['Bài 1: Môn Địa lí với định hướng nghề nghiệp','Bài 2: Sử dụng bản đồ','Bài 3: Trái Đất, thuyết kiến tạo mảng','Bài 4: Hệ quả địa lí các chuyển động của Trái Đất','Bài 5: Thạch quyển','Bài 6: Khí quyển','Bài 7: Thủy quyển','Bài 8: Sinh quyển','Bài 9: Quy luật thống nhất và hoàn chỉnh của vỏ Trái Đất','Bài 10: Quy luật địa đới và phi địa đới','Bài 11: Địa lí dân cư','Bài 12: Đô thị hóa','Bài 13: Địa lí nông nghiệp','Bài 14: Địa lí công nghiệp','Bài 15: Địa lí dịch vụ','Bài 16: Môi trường và phát triển bền vững'],
'GDKT&PL':['Bài 1: Các hoạt động kinh tế cơ bản trong đời sống xã hội','Bài 2: Các chủ thể của nền kinh tế','Bài 3: Thị trường','Bài 4: Cơ chế thị trường','Bài 5: Ngân sách nhà nước','Bài 6: Thuế','Bài 7: Sản xuất kinh doanh và các mô hình sản xuất kinh doanh','Bài 8: Tín dụng và vai trò của tín dụng','Bài 9: Dịch vụ tín dụng','Bài 10: Lập kế hoạch tài chính cá nhân','Bài 11: Hệ thống chính trị nước CHXHCN Việt Nam','Bài 12: Bộ máy nhà nước CHXHCN Việt Nam','Bài 13: Quốc hội, Chủ tịch nước, Chính phủ','Bài 14: Tòa án, Viện kiểm sát, Chính quyền địa phương','Bài 15: Hiến pháp nước CHXHCN Việt Nam','Bài 16: Pháp luật và đời sống'],
'Tin học':['Bài 1: Dữ liệu, thông tin và tri thức','Bài 2: Khí cạnh pháp lí, đạo đức, văn hóa của việc trao đổi thông tin qua mạng','Bài 3: Cấu tạo máy tính','Bài 4: Hệ điều hành','Bài 5: Mạng máy tính','Bài 6: Khai thác thông tin trên internet','Bài 7: Thực hành khai thác thông tin trên internet','Bài 8: Các kiểu dữ liệu cơ bản của Python','Bài 9: Cấu trúc rẽ nhánh','Bài 10: Cấu trúc lặp','Bài 11: Kiểu danh sách','Bài 12: Hàm trong Python','Bài 13: Lập trình giải quyết bài toán','Bài 14: Trí tuệ nhân tạo (AI)'],
'Công nghệ':['Bài 1: Công nghệ và đời sống','Bài 2: Các cuộc cách mạng công nghiệp','Bài 3: Thị trường lao động lĩnh vực công nghệ','Bài 4: Bản vẽ kĩ thuật','Bài 5: Hình chiếu vuông góc','Bài 6: Hình chiếu trục đo','Bài 7: Bản vẽ chi tiết','Bài 8: Bản vẽ lắp','Bài 9: Thiết kế kĩ thuật','Bài 10: Quá trình thiết kế kĩ thuật','Bài 11: Các yếu tố ảnh hưởng đến quá trình thiết kế','Bài 12: Nguyên lí thiết kế','Bài 13: Dự án thiết kế sản phẩm'],
'Hoạt động trải nghiệm':['Chủ đề 1: Phát huy truyền thống nhà trường','Chủ đề 2: Khám phá bản thân','Chủ đề 3: Rèn luyện bản thân','Chủ đề 4: Chủ động, tự tin trong học tập và giao tiếp','Chủ đề 5: Trách nhiệm với gia đình','Chủ đề 6: Tham gia xây dựng cộng đồng','Chủ đề 7: Bảo vệ cảnh quan thiên nhiên và môi trường','Chủ đề 8: Định hướng nghề nghiệp bản thân']
},
'11':{
'Toán':['Bài 1: Góc lượng giác','Bài 2: Các phép biến đổi lượng giác','Bài 3: Hàm số lượng giác','Bài 4: Phương trình lượng giác cơ bản','Bài 5: Dãy số','Bài 6: Cấp số cộng','Bài 7: Cấp số nhân','Bài 8: Mẫu số liệu ghép nhóm','Bài 9: Các số đặc trưng đo xu thế trung tâm','Bài 10: Giới hạn của dãy số','Bài 11: Giới hạn của hàm số','Bài 12: Hàm số liên tục','Bài 13: Điểm, đường thẳng và mặt phẳng trong không gian','Bài 14: Hai đường thẳng chéo nhau và hai đường thẳng song song','Bài 15: Đường thẳng và mặt phẳng song song','Bài 16: Hai mặt phẳng song song','Bài 17: Phép chiếu song song','Bài 18: Lũy thừa','Bài 19: Logarit','Bài 20: Hàm số mũ và hàm số logarit','Bài 21: Phương trình, bất phương trình mũ và logarit','Bài 22: Đạo hàm','Bài 23: Quy tắc tính đạo hàm','Bài 24: Đạo hàm cấp hai','Bài 25: Hai đường thẳng vuông góc','Bài 26: Đường thẳng vuông góc với mặt phẳng','Bài 27: Hai mặt phẳng vuông góc','Bài 28: Góc và khoảng cách trong không gian','Bài 29: Thể tích khối đa diện'],
'Ngữ văn':['Bài 1: Câu chuyện và điểm nhìn trong truyện kể','Bài 2: Khúc tráng ca của bi kịch','Bài 3: Cấu trúc của văn bản nghị luận','Bài 4: Tự sự trong thơ','Bài 5: Quyền năng của người kể chuyện','Bài 6: Nguyễn Du – Những điều trông thấy mà đau đớn lòng','Bài 7: Ghi chép và tưởng tượng trong kí','Bài 8: Cấu trúc của văn bản thông tin','Bài 9: Lựa chọn và hành động','Bài 10: Ôn tập'],
'Tiếng Anh':['Unit 1: A long and healthy life','Unit 2: The generation gap','Unit 3: Cities of the future','Unit 4: ASEAN and Viet Nam','Unit 5: Global warming','Unit 6: Preserving our heritage','Unit 7: Education options for school-leavers','Unit 8: Becoming independent','Unit 9: Social issues','Unit 10: The ecosystem'],
'Vật lí':['Bài 1: Dao động điều hòa','Bài 2: Con lắc lò xo, con lắc đơn','Bài 3: Dao động tắt dần, dao động cưỡng bức, hiện tượng cộng hưởng','Bài 4: Sóng cơ','Bài 5: Giao thoa sóng','Bài 6: Sóng dừng','Bài 7: Điện trường','Bài 8: Cường độ điện trường','Bài 9: Điện thế. Hiệu điện thế','Bài 10: Tụ điện','Bài 11: Dòng điện không đổi','Bài 12: Nguồn điện','Bài 13: Điện trở. Định luật Ohm','Bài 14: Năng lượng điện. Công suất điện','Bài 15: Từ trường','Bài 16: Lực từ','Bài 17: Hiện tượng cảm ứng điện từ','Bài 18: Từ thông. Suất điện động cảm ứng'],
'Hóa học':['Bài 1: Khái niệm về cân bằng hóa học','Bài 2: Cân bằng trong dung dịch nước','Bài 3: Nitrogen','Bài 4: Ammonia và một số hợp chất của nitrogen','Bài 5: Sulfur và sulfur dioxide','Bài 6: Sulfuric acid và muối sulfate','Bài 7: Ôn tập chương 2','Bài 8: Đại cương về hóa học hữu cơ','Bài 9: Phương pháp tách biệt và tinh chế hợp chất hữu cơ','Bài 10: Công thức phân tử hợp chất hữu cơ','Bài 11: Cấu tạo hóa học hợp chất hữu cơ','Bài 12: Alkane','Bài 13: Hydrocarbon không no','Bài 14: Arene (Hydrocarbon thơm)','Bài 15: Dẫn xuất halogen','Bài 16: Alcohol','Bài 17: Phenol','Bài 18: Aldehyde và ketone','Bài 19: Carboxylic acid'],
'Sinh học':['Bài 1: Khái quát về trao đổi chất và chuyển hóa năng lượng','Bài 2: Trao đổi nước và khoáng ở thực vật','Bài 3: Thực hành trao đổi nước và khoáng','Bài 4: Quang hợp ở thực vật','Bài 5: Hô hấp ở thực vật','Bài 6: Dinh dưỡng và tiêu hóa ở động vật','Bài 7: Hô hấp ở động vật','Bài 8: Hệ tuần hoàn ở động vật','Bài 9: Cân bằng nội môi','Bài 10: Khái quát về cảm ứng ở sinh vật','Bài 11: Cảm ứng ở thực vật','Bài 12: Cảm ứng ở động vật','Bài 13: Tập tính ở động vật','Bài 14: Sinh trưởng và phát triển ở thực vật','Bài 15: Sinh trưởng và phát triển ở động vật','Bài 16: Sinh sản ở thực vật','Bài 17: Sinh sản ở động vật','Bài 18: Mối quan hệ giữa các quá trình sinh lí'],
'Lịch sử':['Bài 1: Cách mạng tư sản và sự phát triển của CNTB','Bài 2: Chủ nghĩa tư bản hiện đại','Bài 3: Sự hình thành Liên bang Xô viết','Bài 4: Quá trình xây dựng chủ nghĩa xã hội (từ 1921 đến nay)','Bài 5: Chủ nghĩa xã hội từ năm 1991 đến nay','Bài 6: Hành trình đi đến độc lập dân tộc ở Đông Nam Á','Bài 7: Quá trình xây dựng và phát triển ở Đông Nam Á','Bài 8: Nước Đại Việt thời Lê Sơ','Bài 9: Nước Đại Việt thời Mạc','Bài 10: Phong trào Tây Sơn','Bài 11: Việt Nam nửa đầu kỉ XIX','Bài 12: Các cuộc cải cách ở Việt Nam','Bài 13: Vai trò của Biển Đông đối với Việt Nam','Bài 14: Lịch sử bảo vệ chủ quyền Biển Đông'],
'Địa lí':['Bài 1: Sự khác biệt về trình độ phát triển KT-XH của các nhóm nước','Bài 2: Toàn cầu hóa và khu vực hóa kinh tế','Bài 3: Các tổ chức khu vực và quốc tế','Bài 4: An ninh toàn cầu và bảo vệ hòa bình thế giới','Bài 5: Khu vực Mỹ La-tinh','Bài 6: Liên minh châu Âu (EU)','Bài 7: Khu vực Đông Nam Á','Bài 8: Tây Á','Bài 9: Hợp chủng quốc Hoa Kỳ','Bài 10: Liên bang Nga','Bài 11: Nhật Bản','Bài 12: Cộng hòa nhân dân Trung Hoa','Bài 13: Australia'],
'GDKT&PL':['Bài 1: Cạnh tranh trong nền kinh tế thị trường','Bài 2: Cung, cầu trong nền kinh tế thị trường','Bài 3: Lạm phát','Bài 4: Thất nghiệp','Bài 5: Thị trường lao động và việc làm','Bài 6: Ý tưởng kinh doanh','Bài 7: Năng lực quản lí tài chính','Bài 8: Quyền bình đẳng của công dân trước pháp luật','Bài 9: Bình đẳng giới','Bài 10: Quyền dân chủ của công dân','Bài 11: Quyền và nghĩa vụ của công dân về kinh tế','Bài 12: Quyền và nghĩa vụ của công dân về văn hóa xã hội','Bài 13: Quyền và nghĩa vụ của công dân trong bảo vệ Tổ quốc'],
'Tin học':['Bài 1: Kiến trúc máy tính và hệ điều hành','Bài 2: Thiết bị ngoại vi','Bài 3: Quản lí tệp và thư mục','Bài 4: Khám phá internet','Bài 5: Mạng máy tính','Bài 6: Bảo mật thông tin trên mạng','Bài 7: Cơ sở dữ liệu','Bài 8: Hệ quản trị CSDL','Bài 9: Ngôn ngữ truy vấn SQL','Bài 10: Lập trình với Python: Xử lí xâu kí tự','Bài 11: Kiểu mảng hai chiều','Bài 12: Lập trình giải bài toán tối ưu','Bài 13: Trí tuệ nhân tạo và tương lai'],
'Công nghệ':['Bài 1: Đại cương về cơ khí chế tạo','Bài 2: Vật liệu cơ khí','Bài 3: Các phương pháp gia công cơ khí','Bài 4: Quá trình sản xuất cơ khí','Bài 5: Tự động hóa trong sản xuất cơ khí','Bài 6: Đại cương về kĩ thuật điện','Bài 7: Mạch điện xoay chiều','Bài 8: Máy điện xoay chiều','Bài 9: Mạng điện sản xuất quy mô nhỏ','Bài 10: Ngành nghề lĩnh vực cơ khí và kĩ thuật điện'],
'Hoạt động trải nghiệm':['Chủ đề 1: Thích ứng với sự thay đổi','Chủ đề 2: Tự tin và trách nhiệm','Chủ đề 3: Xây dựng mối quan hệ tốt đẹp','Chủ đề 4: Tích cực học tập và rèn luyện','Chủ đề 5: Tham gia hoạt động xã hội','Chủ đề 6: Quản lí tài chính cá nhân','Chủ đề 7: Định hướng nghề nghiệp tương lai','Chủ đề 8: Bảo vệ môi trường và ứng phó với biến đổi khí hậu']
},
'12':{
'Toán':['Bài 1: Tính đơn điệu và cực trị của hàm số','Bài 2: Giá trị lớn nhất, giá trị nhỏ nhất của hàm số','Bài 3: Đường tiệm cận của đồ thị hàm số','Bài 4: Khảo sát sự biến thiên và vẽ đồ thị của hàm số','Bài 5: Ứng dụng đạo hàm để giải quyết một số vấn đề thực tiễn','Bài 6: Vectơ trong không gian','Bài 7: Hệ tọa độ trong không gian','Bài 8: Biểu thức tọa độ của các phép toán vectơ','Bài 9: Khoảng biến thiên và khoảng tứ phân vị của mẫu số liệu ghép nhóm','Bài 10: Phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm','Bài 11: Nguyên hàm','Bài 12: Tích phân','Bài 13: Ứng dụng hình học của tích phân','Bài 14: Phương trình mặt phẳng','Bài 15: Phương trình đường thẳng trong không gian','Bài 16: Mặt cầu','Bài 17: Công thức cộng xác suất','Bài 18: Công thức nhân xác suất'],
'Ngữ văn':['Bài 1: Khả năng tưởng tượng và hư cấu trong truyện ngắn','Bài 2: Vẻ đẹp của thơ ca truyền thống','Bài 3: Nghệ thuật lập luận trong văn nghị luận','Bài 4: Sự phong phú của truyện kể dân gian','Bài 5: Bi kịch và khát vọng của con người trong sân khấu','Bài 6: Hồ Chí Minh – Một tâm hồn lớn, một trí tuệ lớn','Bài 7: Tầm nhìn thời đại trong tùy bút, tản văn','Bài 8: Thông tin đa chiều trong văn bản thông tin','Bài 9: Văn học hiện đại và những vấn đề nhân sinh','Bài 10: Tổng kết lịch sử văn học Việt Nam'],
'Tiếng Anh':['Unit 1: Life stories we admire','Unit 2: A multicultural world','Unit 3: Green living','Unit 4: Urbanisation','Unit 5: The world of work','Unit 6: Artificial intelligence','Unit 7: Lifelong learning','Unit 8: Biodiversity conservation','Unit 9: Career paths','Unit 10: Independent life'],
'Vật lí':['Bài 1: Sự chuyển thể của chất','Bài 2: Nội năng và định luật 1 Nhiệt động lực học','Bài 3: Nhiệt dung riêng, nhiệt nóng chảy riêng, nhiệt hóa hơi riêng','Bài 4: Khí lí tưởng','Bài 5: Các định luật chất khí','Bài 6: Lực từ trường','Bài 7: Cảm ứng từ','Bài 8: Lực Lorentz','Bài 9: Hiện tượng tự cảm','Bài 10: Dòng điện xoay chiều','Bài 11: Công suất của mạch điện xoay chiều','Bài 12: Máy biến áp. Truyền tải điện năng','Bài 13: Sóng điện từ','Bài 14: Thuyết lượng tử ánh sáng','Bài 15: Hiện tượng quang điện','Bài 16: Mẫu nguyên tử Bohr','Bài 17: Cấu trúc hạt nhân','Bài 18: Phóng xạ','Bài 19: Phản ứng hạt nhân','Bài 20: Năng lượng hạt nhân'],
'Hóa học':['Bài 1: Ester – Lipid','Bài 2: Xà phòng và chất giặt rửa','Bài 3: Glucose và fructose','Bài 4: Saccharose và maltose','Bài 5: Tinh bột và cellulose','Bài 6: Amino acid','Bài 7: Peptide và protein','Bài 8: Polymer và vật liệu polymer','Bài 9: Thế điện cực chuẩn của kim loại','Bài 10: Pin điện hóa','Bài 11: Sự điện phân','Bài 12: Cấu tạo và tính chất vật lí của kim loại','Bài 13: Tính chất hóa học của kim loại','Bài 14: Ăn mòn kim loại','Bài 15: Nguyên tắc và phương pháp điều chế kim loại','Bài 16: Nhóm IA và nhóm IIA','Bài 17: Sắt và hợp chất của sắt','Bài 18: Đồng và hợp chất của đồng','Bài 19: Hóa học và phát triển bền vững','Bài 20: Ôn tập cuối năm'],
'Sinh học':['Bài 1: Gene và sự biểu hiện của gene','Bài 2: Điều hòa hoạt động của gene','Bài 3: Hệ gene và đột biến gene','Bài 4: Nhiễm sắc thể và đột biến nhiễm sắc thể','Bài 5: Di truyền học Mendel','Bài 6: Liên kết gene và hoán vị gene','Bài 7: Di truyền liên kết với giới tính và di truyền ngoài nhân','Bài 8: Ảnh hưởng của môi trường đến biểu hiện của gene','Bài 9: Di truyền quần thể','Bài 10: Di truyền học người','Bài 11: Tạo giống biến đổi gene','Bài 12: Bằng chứng tiến hóa','Bài 13: Học thuyết tiến hóa tổng hợp hiện đại','Bài 14: Quá trình hình thành loài','Bài 15: Nguồn gốc sự sống và lịch sử phát triển của sinh giới','Bài 16: Quần thể sinh vật','Bài 17: Quần xã sinh vật','Bài 18: Hệ sinh thái','Bài 19: Sinh quyển và các khu sinh học','Bài 20: Sinh thái học phục hồi và bảo tồn đa dạng sinh học'],
'Lịch sử':['Bài 1: Trật tự thế giới sau Chiến tranh thế giới thứ hai','Bài 2: Sự hình thành trật tự thế giới đa cực','Bài 3: ASEAN - Những chặng đường lịch sử','Bài 4: ASEAN - Hợp tác và phát triển','Bài 5: Lịch sử cách mạng Việt Nam 1945-1975','Bài 6: Hoạt động đối ngoại của Việt Nam trong kháng chiến','Bài 7: Khôi phục và phát triển đất nước sau 1975','Bài 8: Công cuộc Đổi mới ở Việt Nam','Bài 9: Đối ngoại Việt Nam trong thời kì Đổi mới','Bài 10: Hồ Chí Minh - Anh hùng giải phóng dân tộc','Bài 11: Võ Nguyên Giáp - Đại tướng của nhân dân','Bài 12: Bảo vệ chủ quyền biên giới, biển đảo quốc gia'],
'Địa lí':['Bài 1: Đặc điểm vị trí địa lí và lãnh thổ Việt Nam','Bài 2: Đặc điểm chung của tự nhiên Việt Nam','Bài 3: Sự phân hóa đa dạng của thiên nhiên','Bài 4: Vấn đề sử dụng và bảo vệ tự nhiên','Bài 5: Dân cư và lao động Việt Nam','Bài 6: Đô thị hóa ở Việt Nam','Bài 7: Chuyển dịch cơ cấu kinh tế','Bài 8: Vấn đề phát triển nông nghiệp','Bài 9: Vấn đề phát triển lâm nghiệp và thủy sản','Bài 10: Tổ chức lãnh thổ nông nghiệp','Bài 11: Vấn đề phát triển công nghiệp','Bài 12: Tổ chức lãnh thổ công nghiệp','Bài 13: Giao thông vận tải và thông tin liên lạc','Bài 14: Thương mại và du lịch','Bài 15: Vùng Trung du và miền núi Bắc Bộ','Bài 16: Vùng Đồng bằng sông Hồng','Bài 17: Vùng Bắc Trung Bộ và Duyên hải miền Trung','Bài 18: Vùng Tây Nguyên','Bài 19: Vùng Đông Nam Bộ','Bài 20: Vùng Đồng bằng sông Cửu Long','Bài 21: Phát triển kinh tế an ninh quốc phòng biển đảo'],
'GDKT&PL':['Bài 1: Tăng trưởng và phát triển kinh tế','Bài 2: Hội nhập kinh tế quốc tế','Bài 3: Bảo hiểm','Bài 4: Hệ thống an sinh xã hội','Bài 5: Quản lí thu, chi trong gia đình','Bài 6: Lập kế hoạch kinh doanh','Bài 7: Quản lí doanh nghiệp','Bài 8: Hiến pháp về quyền và nghĩa vụ cơ bản của công dân','Bài 9: Pháp luật về quyền con người','Bài 10: Pháp luật về dân sự','Bài 11: Hợp đồng dân sự','Bài 12: Pháp luật về hình sự','Bài 13: Tội phạm và hình phạt','Bài 14: Pháp luật về hành chính','Bài 15: Xử lí vi phạm hành chính','Bài 16: Giải quyết tranh chấp'],
'Tin học':['Bài 1: Hệ thống mạng máy tính','Bài 2: Quản trị mạng cục bộ','Bài 3: Chia sẻ tài nguyên mạng','Bài 4: Internet vạn vật (IoT)','Bài 5: Ứng dụng IoT trong đời sống','Bài 6: Cơ sở dữ liệu quan hệ','Bài 7: Ngôn ngữ SQL nâng cao','Bài 8: Lập trình với thư viện đồ họa','Bài 9: Xây dựng giao diện người dùng','Bài 10: Lập trình trò chơi đơn giản','Bài 11: Phân tích dữ liệu với Python','Bài 12: Trực quan hóa dữ liệu lớn','Bài 13: Hướng nghiệp lĩnh vực công nghệ thông tin'],
'Công nghệ':['Bài 1: Tự động hóa trong công nghiệp','Bài 2: Robot công nghiệp','Bài 3: Ứng dụng của vi điều khiển','Bài 4: Lập trình vi điều khiển','Bài 5: Năng lượng tái tạo','Bài 6: Hệ thống điện năng lượng mặt trời','Bài 7: Mạng điện thông minh','Bài 8: Kĩ thuật vi mạch','Bài 9: Thiết kế mạch in','Bài 10: Khởi nghiệp trong lĩnh vực kĩ thuật']
}
};
